config/routes.rb
Rails.application.routes.draw do
  root to: 'tasks#index'
  
  get 'tasklists/create'
  get 'tasklists/destroy'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  get 'signup', to: 'users#new'
  resources :users, only: [:index, :show, :create]
  
  resources :tasks
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
  validates :content, presence: true, length: { maximum: 255 }
  validates :status, presence: true, length: { maximum: 10 }
end

app/models/tasklist.rb
class Tasklist < ApplicationRecord
  belongs_to :user

  validates :content, presence: true, length: { maximum: 255 }
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email.downcase! }
  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  
  has_many :tasks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  include SessionsHelper
  
  private
  
  def require_user_logged_in
    unless logged_in?
      redirect_to login_url
    end
  end
  
  def counts(user)
    @count_tasks = user.tasks.count
  end
    
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    email = params[:session][:email].downcase
    password = params[:session][:password]
    if login(email, password)
      flash[:success] = 'ログインに成功しました'
      redirect_to @user
    else
      flash.now[:danger] = 'ログインに失敗しました'
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = 'ログアウトしました'
    redirect_to root_url
  end
  
  private
  
  def login(email, password)
    @user = User.find_by(email: email)
    if @user && @user.authenticate(password)
      session[:user_id] = @user.id
      return true
    else
      return false
    end
  end
end

app/controllers/tasklists_controller.rb
class TasklistsController < ApplicationController
  before_action :require_user_logged_in
  
  def create
    @tasklist = current_user.tasklists.build(tasklist_params)
    if @tasklist.save
      flash[:success] = 'タスクを作成しました'
      redirect_to root_url
    else
      @tasklists = current_user.tasklists.order(id: :desc)
      flash.now[:danger] = 'タスクの作成に失敗しました'
      render 'toppages/index'
    end
  end
  
  def destroy
    @tasklist.destroy
    flash[:success] = 'タスクを削除しました。'
    redirect_back(fallback_location: root_path)
  end
  
  private
  
  def tasklist_params
    params.require(:tasklist).permit(:content)
  end
  
  def current_user
    @tasklist = current_user.tasklists.find_by(id: params[:id])
    unless @tasklist
      redirect_to root_url
    end
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
 before_action :set_task, only: [:show, :edit, :update, :destroy]
 
  def index
   @tasks = Task.all.order(id: :desc)
  end

  def show
   @task = Task.find(params[:id])
  end

  def new
   @task = Task.new
  end

  def create
   @task = current_user.tasks.build(task_params)
    if @task.save
     flash[:success] = 'Taskが正常に作成されました'
     redirect_to @task
    else
     flash.now[:danger] = 'Taskは作成されませんでした'
     render :new
    end
  end

  def edit
  end

  def update
   @task = Task.find(params[:id])
   
    if @task.update(task_params)
     flash[:success] = 'Taskは正常に更新されました'
     redirect_to @task
    else
     flash[:danger] = 'Taskは更新されませんでした'
     render :edit
    end
  end

  def destroy
   @task.destroy
   
   flash[:success] = 'Taskは正常に削除されました'
   redirect_to tasks_url
  end

 private

 # Strong Parameter
  def set_task
   @task = Task.find(params[:id])
  end
  
  def task_params
   params.require(:task).permit(:content, :status)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user_logged_in, only: [:index, :show]
  
  def index
    #@users = User.order(id: :desc)
  end

  def show
    @user = User.find(params[:id])
    Task.all.order(id: :desc)
    counts(@user)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    
    if @user.save
      flash[:success] = 'ユーザーを登録しました。'
      redirect_to @user
    else
      flash.now[:danger] = 'ユーザーの登録に失敗しました。'
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  
  def logged_in?
    !!current_user
  end
end

app/helpers/tasklists_helper.rb
module TasklistsHelper
end

app/helpers/toppages_helper.rb
module ToppagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
   def gravatar_url(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
   end
end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div id="error_explanation" class="alert alert-warning">
    <ul class="mb-0">
      <% model.errors.full_tasks.each do |task| %>
        <li><%= task %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/layouts/_navbar.html.erb
<header class="mb-4">
  <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
    <div class="container-fluid ps-5 pe-5">
      <a class="navbar-brand" href="/">Tasklists</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent">
        <span class="navbar-toggler-icon"></span>
      </button>

    <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
    <% if logged_in? %>
      <div class="btn-group">
        <ul class="navbar-nav">
          <li class="ms-3"><%= link_to 'Users', users_path, class: 'nav-link' %></li>
        </ul>
        <button type="button" class="btn btn-dark dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false"><%= current_user.name %></button>
        <ul class="dropdown-menu dropdown-menu-end">
          <li class="dropdown-item"><%= link_to 'My profile', user_path(current_user), class: 'nav-link' %></li>
          <li class="dropdown-divider"></li>
          <li class="dropdown-item"><%= link_to 'Logout', logout_path, method: :delete, class: 'nav-link' %></li>
        </ul>
      </div>
    <% else %>
        <ul class="navbar-nav">
          <li class="nav-item"><%= link_to 'SignUp', signup_path, class: 'nav-link' %></li>
          <li class="nav-item"><%= link_to 'Login', login_path, class: 'nav-link' %></li>
        </ul>
    <% end %>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tasklists</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js"></script>
  </head>

  <body data-turbolinks="false">
    <%= render 'layouts/navbar' %>

    <div class="container">
      <%= render 'layouts/flash_messages' %>

      <%= yield %>
    </div>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_with(model: task) do |f| %>
  <% if task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(task.errors.count, "error") %> prohibited this message from being saved:</h2>
      
      <ul>
        <% task.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.label :content, 'タスク' %>
  <%= f.text_field :content %>
  
  <%= f.label :status, 'ステータス' %>
  <%= f.text_field :status %>

  <%= f.submit '作成' %>
<% end %>

app/views/tasks/edit.html.erb
<h1>タスク編集ページ</h1>

<%= render 'form', task: @task %>

<%= link_to '一覧に戻る', tasks_path %>

app/views/tasks/index.html.erb
<% if logged_in? %>
  <p>ログイン完了ユーザー: <%= current_user.name %></p>
<% else %>
  <div class="bg-secondary p-3 p-sm-5 my-4 rounded">
    <div class="text-center text-white">
      <h1>Welcome to the Tasklists</h1>
      <%= link_to 'Sign Up Now!', signup_path, class: 'btn btn-lg btn-primary' %>
    </div>
  </div>
<% end %>

app/views/tasks/new.html.erb
<h1>タスク新規作成ページ</h1>

<%= render 'form', task: @task %>

<%= link_to '一覧に戻る', tasks_path %>

app/views/tasks/show.html.erb
<h1>id: <%= @task.id %> のタスク詳細ページ</h1>

<p>タスク: <%= @task.content %></p>
<p>ステータス: <%= @task.status %></p>

<%= link_to '一覧に戻る', tasks_path %>
<%= link_to 'このタスクを編集する', edit_task_path(@task) %>
<%= link_to 'このタスクを削除する', @task, method: :delete, data: { confirm: '本当に削除してよろしいですか？' } %>

app/views/users/_users.html.erb
<% if users.any? %>
  <ul class="list-unstyled">
    <% users.each do |user| %>
      <li class="mb-3 d-flex">
        <img class="rounded me-2" src="<%= gravatar_url(user, { size: 64 }) %>" alt="">
        <div>
          <div>
            <%= user.name %>
          </div>
          <div>
            <p><%= link_to 'View Profiles', user_path(user), class: "text-decoration-none" %></p>
          </div>
        </div>
      </li>
    <% end %>
  </ul>
<% end %>

app/views/users/index.html.erb
<%#= render 'users', users: @users %>

app/views/users/new.html.erb
<div class="text-center">
  <h1>Sign up</h1>
</div>

<div class="row">
  <div class="col-sm-6 offset-sm-3">

    <%= form_with(model: @user) do |f| %>
      <%= render 'layouts/error_messages', model: f.object %>

      <div class="mb-3">
        <%= f.label :name, 'Name' %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>

      <div class="mb-3">
        <%= f.label :email, 'Email' %>
        <%= f.email_field :email, class: 'form-control' %>
      </div>

      <div class="mb-3">
        <%= f.label :password, 'Password' %>
        <%= f.password_field :password, class: 'form-control' %>
      </div>

      <div class="mb-3">
        <%= f.label :password_confirmation, 'Confirmation' %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>
      </div>

      <%= f.submit 'Sign up', class: 'btn btn-primary w-100' %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="row">
  <aside class="col-sm-4">
    <div class="card">
      <div class="card-header">
        <h3 class="card-title"><%= @user.name %></h3>
      </div>
      <div class="card-body">
        <img class="rounded img-fluid" src="<%= gravatar_url(@user, { size: 500 }) %>" alt="">
      </div>
    </div>
  </aside>
  <div class="col-sm-8">
    <ul class="nav nav-tabs nav-justified mb-3">
      <li class="nav-item"><a href="<%= user_path(@user) %>" class="nav-link <%= 'active' if current_page?(user_path(@user)) %>">Tasklists　<span class="badge bg-secondary"><%= @count_tasks %></span></a></li>
    </ul>
  </div>
</div>